###############################################################################
#
#   CONFIGURATION FILE FOR RUNNING EXPERIMENT
#
###############################################################################


############################################
#   EXPERIMENT
############################################
experiment:
  # Random seed
  seed: 73

  # Maximum number of epochs to run training for
  max_epochs: 512

  # Precision
  precision: 32

  # Supervision regularization weight
  supervision_weight: 0.1


############################################
#   DATASETS
############################################
dataset:
  # Path to dataset
  root: "data/"

  # Split ratio in [0, 1] - sum must be == 1
  split:
    train: 0.8
    val: 0.2

  # Dataloading specifications
  dataloader:
    # Number of frames per batch
    batch_size: 32

    # Number of workers for loading
    num_workers: 1


############################################
#   NETWORK
############################################
model:
  generator:
    # Input image size
    input_size:
      - 3           # channels
      - 127         # height
      - 127         # width

    # Number of channels of output image
    out_channels: 3

    # Nb of filters from first to last encoding convolutional block
    enc_filters:
      - 64
      - 128
      - 256
      - 512
      - 1024

    # Parameters of encoding convolutional blocks
    enc_kwargs:
      - {bn: False, relu: False}
      - {}
      - {}
      - {}
      - {stride: 1}

    # Nb of filters from first to last decoding convolutional block
    dec_filters:
      - 512
      - 256
      - 128
      - 64
      - 64


    # Parameters of decoding convolutional blocks
    dec_kwargs:
      - {dropout: 0.4, kernel_size: 2, stride: 1, padding: 0}
      - dropout: 0.4
      - {}
      - {}
      - {relu: False, bn: False}


  discriminator:
    # Input image size
    input_size:
      - 6           # channels
      - 127         # height
      - 127         # width

    # Nb of filters from first to last encoding convolutional block
    n_filters:
      - 128
      - 256
      - 512
      - 512
      - 1

    # Parameters of convolutional blocks
    conv_kwargs:
      - bn: False
      - {}
      - {}
      - {stride: 1}
      - {stride: 1, bn: False, relu: False}




############################################
#   OPTIMIZER - LR SCHEDULER
############################################
# Specify optimizer params for LightningModule.configure_optimizers method
optimizer:
  generator:
    lr: 0.0002
    betas:
      - 0.5
      - 0.999
  discriminator:
    lr: 0.0002
    betas:
      - 0.5
      - 0.999
    weight_decay: 0.000001


# Specify lr scheduler params for LightningModule.configure_optimizers method
lr_scheduler:
  generator:
    gamma: 0.99
  discriminator:
    gamma: 0.99



############################################
#   CALLBACKS
############################################
# Specs of checkpoint saving callback
model_checkpoint:
  # Quantity to monitor
  monitor: 'val_loss'

  # Save top k models
  save_top_k: 5

  # Monitor modality
  mode: 'min'
